version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://production-review-tool.herokuapp.com/api/buildNotification
jobs:
  build:
    working_directory: ~/chaostest
    docker:
      - image: circleci/node:latest        
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update -qq      
      - run: 
          name: Install Node dependencies
          command: |
             npm install
      - run: bash .circleci/setup-heroku.sh
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
            fi
